apiVersion: v1
kind: Service
metadata:
  name: book-catalog-db
  labels:
    app.kubernetes.io/name: book-catalog-db
spec:
  selector:
    app.kubernetes.io/name: book-catalog-db
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
