apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
  labels:
    app.kubernetes.io/name: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: book-catalog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: docker.io/mayasii/book-catalog:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: book-catalog-config
            - secretRef:
                name: book-catalog-secret
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 250m, memory: 128Mi }
